# Generated by Django 3.0.4 on 2020-03-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_salesorder_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='bubun',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
